# -*- coding: utf-8 -*-
"""FINAL_After Session 2PYF_Project_LearnerNotebook2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTXWCUxDxncQzg3MTHOBjCIF5AMwZQji

# Project Python Foundations: FoodHub Data Analysis

**Marks: 60**

### Context

The number of restaurants in New York is increasing day by day. Lots of students and busy professionals rely on those restaurants due to their hectic lifestyles. Online food delivery service is a great option for them. It provides them with good food from their favorite restaurants. A food aggregator company FoodHub offers access to multiple restaurants through a single smartphone app.

The app allows the restaurants to receive a direct online order from a customer. The app assigns a delivery person from the company to pick up the order after it is confirmed by the restaurant. The delivery person then uses the map to reach the restaurant and waits for the food package. Once the food package is handed over to the delivery person, he/she confirms the pick-up in the app and travels to the customer's location to deliver the food. The delivery person confirms the drop-off in the app after delivering the food package to the customer. The customer can rate the order in the app. The food aggregator earns money by collecting a fixed margin of the delivery order from the restaurants.

### Objective

The food aggregator company has stored the data of the different orders made by the registered customers in their online portal. They want to analyze the data to get a fair idea about the demand of different restaurants which will help them in enhancing their customer experience. Suppose you are hired as a Data Scientist in this company and the Data Science team has shared some of the key questions that need to be answered. Perform the data analysis to find answers to these questions that will help the company to improve the business.

### Data Description

The data contains the different data related to a food order. The detailed data dictionary is given below.

### Data Dictionary

* order_id: Unique ID of the order
* customer_id: ID of the customer who ordered the food
* restaurant_name: Name of the restaurant
* cuisine_type: Cuisine ordered by the customer
* cost: Cost of the order
* day_of_the_week: Indicates whether the order is placed on a weekday or weekend (The weekday is from Monday to Friday and the weekend is Saturday and Sunday)
* rating: Rating given by the customer out of 5
* food_preparation_time: Time (in minutes) taken by the restaurant to prepare the food. This is calculated by taking the difference between the timestamps of the restaurant's order confirmation and the delivery person's pick-up confirmation.
* delivery_time: Time (in minutes) taken by the delivery person to deliver the food package. This is calculated by taking the difference between the timestamps of the delivery person's pick-up confirmation and drop-off information

### Let us start by importing the required libraries
"""

# import libraries for data manipulation
import streamlit as st
import numpy as np
import pandas as pd

st.set_page_config(
    page_title="FoodHub Data Analysis",
    page_icon="🍴",
    layout="wide"
)

st.title("🍴 FoodHub Data Analysis")
st.markdown(
    """
    ### Understanding FoodHub's Customers, Restaurants & Orders

    This interactive dashboard analyzes FoodHub order data to identify
    customer preferences, restaurant demand, pricing, and delivery patterns.
    """
)

st.divider()

# import libraries for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

"""### Understanding the structure of the data"""

# uncomment and run the following lines for Google Colab
# from google.colab import drive
# drive.mount('/content/drive')

# read the data# read the data
df = pd.read_csv('foodhub_order.csv')

# Add total_time column immediately after loading data
df['total_time'] = df['food_preparation_time'] + df['delivery_time']

# Dashboard summary
st.subheader("📊 FoodHub at a Glance")

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Total Orders", f"{len(df):,}")

with col2:
    st.metric("Customers", f"{df['customer_id'].nunique():,}")

with col3:
    st.metric("Restaurants", f"{df['restaurant_name'].nunique():,}")

with col4:
    st.metric("Avg. Order Cost", f"${df['cost_of_the_order'].mean():.2f}")

st.divider()

# returns the first 5 rows
df.head()
    st.metric("Avg. Order Cost", f"${df['cost_of_the_order'].mean():.2f}")

st.divider()
df['total_time'] = df['food_preparation_time'] + df['delivery_time']
# returns the first 5 rows
df.head()

"""#### Observations:

* The DataFrame has 9 columns as mentioned in the Data Dictionary.
* Data in each row corresponds to the order placed by a customer.

### **Question 1:** How many rows and columns are present in the data? [0.5 mark]
"""

df.shape

"""#### Observations:
* The data can be used to find trends.
* There are 9 rows and 1898 columns.

### **Question 2:** What are the datatypes of the different columns in the dataset? (The info() function can be used) [0.5 mark]
"""

# Use info() to print a concise summary of the DataFrame
df.info()

"""#### Observations:
*   There is no missing values
*   Each data type is either a integer, object or float(number with decimals or fractions).
*  Five of the columns are related to numbers and one column is related to objects which means it is a string or text.
*   Rating is an object so we should change it.
* Cost of the order is stored as a float because it contains decimal values.
* The data types are generally appropriate for the type of information represented, making the dataset suitable for further analysis.

### **Question 3:** Are there any missing values in the data? If yes, treat them using an appropriate method. [1 mark]
"""

df.isnull().sum()

"""#### Observations:

* There are no missing values.
*   Not given is still data given. It is not null or missing value.
* This means that the data will be useful, does not need to be altered and is more reliable for analysis.
*Helps prevent bias from missing information.

### **Question 4:** Check the statistical summary of the data. What is the minimum, average, and maximum time it takes for food to be prepared once an order is placed? [2 marks]
"""

min_prep_time = df['food_preparation_time'].min()
max_prep_time = df['food_preparation_time'].max()
mean_prep_time = df['food_preparation_time'].mean()

print(f"Minimum food preparation time: {min_prep_time} minutes")
print(f"Maximum food preparation time: {max_prep_time} minutes")
print(f"Average food preparation time: {mean_prep_time:.2f} minutes")

"""#### Observations:

* The average food preparation time is fairly consistent.

* There is not a huge difference between the minimum food preparation time and the maximum food preparation time.
* The average food preparation time is 27.37 minutes.
* Their restaurant preparation times are fairly predictable.

### **Question 5:** How many orders are not rated? [1 mark]
"""

print(df[df['rating'] == 'Not given']['rating'].count())

"""#### Observations:
* Less than half the orders are not rated.

* This shows that customers usually rate their order.

* 736 of the 1898 orders do not have a rating.

### Exploratory Data Analysis (EDA)

### Univariate Analysis

### **Question 6:** Explore all the variables and provide observations on their distributions. (Generally, histograms, boxplots, countplots, etc. are used for univariate exploration.) [9 marks]
"""

df.nunique()

"""## **Order ID**"""

pd.to_numeric(df['Unnamed: 0'], errors='coerce').nunique()

df_cleaned = df.copy()
df_cleaned.rename(columns={'Unnamed: 0': 'order_id'}, inplace=True)
df_cleaned['order_id'] = pd.to_numeric(df_cleaned['order_id'], errors='coerce')
df_cleaned.dropna(subset=['order_id'], inplace=True)
df_cleaned['order_id'] = df_cleaned['order_id'].astype(int)
sns.boxplot(data=df_cleaned, x='order_id')
plt.show()

"""Observations:

* The order ID is evenly distributed. There are no outliers.

# **Customer ID**
"""

df['customer_id'].nunique()

sns.boxplot(data=df, x='customer_id')
plt.show()

"""Observations:

* The customer ID does not have any outliers. The data shows that it is fairly balanced.
* Based on the number of orders (1898), there are only 1200 unique customers which means that orders are usually made by the same people. There is repeat purchasing.

# **Delivery Time**
"""

df['delivery_time'].describe()

df['delivery_time'].nunique()

sns.boxplot(data=df, x='delivery_time')
plt.show()

"""# Observations

* Delivery time is fairly consistent.
* Customers wait an average of 24 minutes for delivery.

# **Restaurant Name**
"""

df['restaurant_name'].describe()

df['restaurant_name'].value_counts()

df['restaurant_name'].nunique()

sns.boxplot(data=df, x='restaurant_name')
plt.show()

"""# Observations

* Shake Shack has the most number of orders.
* There is a large customer demand on specific restaurants.

# **Cuisine**
"""

df['cuisine_type'].nunique()

df['cuisine_type'].describe()

df['cuisine_type'].value_counts()

"""Observations:

* The cuisine types that is most popular are American food, Japanese food, and Italian Food.
* Out of the 1898 orders, 584 of those orders are American food.

# **Cost of Order**
"""

mean_cost_of_order = df['cost_of_the_order'].mean()
print(f"The mean cost of the order is: {mean_cost_of_order:.2f}")

min_cost_of_order = df['cost_of_the_order'].min()
print(f"The minimum cost of the order is: {min_cost_of_order:.2f}")

max_cost_of_order = df['cost_of_the_order'].max()
print(f"The maximum cost of the order is: ${max_cost_of_order:.2f}")

df['cost_of_the_order'].describe()

plt.figure(figsize=(10, 6))
sns.histplot(df['cost_of_the_order'], bins=20, kde=True)
plt.title('Distribution of Cost of the Order')
plt.xlabel('Cost of the Order ($)')
plt.ylabel('Frequency')
plt.show()

"""Observations:

* The higher the cost of the order, the fewer orders you have.
* The price that causes the highest frequency in orders is about $12.

* The average cost of order is $16.

# **Days of the week**
"""

df.head()

df['day_of_the_week'].describe()

plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='day_of_the_week', palette='viridis', hue='day_of_the_week', legend=False)
plt.title('Number of Orders by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Number of Orders')
plt.show()

df['day_of_the_week'].value_counts(normalize = True)

"""Observations:

* The plot shows that the number of orders on the weekend is higher than the ones during the weekday.

# **Rating**
"""

df['rating'].nunique()

plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='rating', palette='viridis', hue='rating', legend=False)
plt.title('Distribution of Customer Ratings')
plt.xlabel('Rating')
plt.ylabel('Number of Orders')
plt.show()

df['rating'] != 'Not given'

"""Observations:

*   This shows that a majority of customers do not rate their orders.
*  Rating a 5 is the most frequent rating which means that customers are generally satisfied with their orders.

# **Food Preparation Time**
"""

df['food_preparation_time'].nunique()

df['food_preparation_time'].describe()

plt.figure(figsize=(10, 6))
sns.histplot(df['food_preparation_time'], bins=15, kde=True)
plt.title('Distribution of Food Preparation Time')
plt.xlabel('Food Preparation Time (minutes)')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt

plt.hist(df['food_preparation_time'], bins=10)

plt.xlabel('Food Preparation Time (minutes)')
plt.ylabel('Frequency')
plt.title('Distribution of Food Preparation Times')

plt.show()

average_prep_time = df_cleaned.groupby(
    ['restaurant_name', 'cuisine_type']
)['food_preparation_time'].mean().reset_index()

average_prep_time['food_preparation_time'] = average_prep_time[
    'food_preparation_time'
].round(2)

average_prep_time = average_prep_time.sort_values(
    'food_preparation_time',
    ascending=False
)

average_prep_time

top_longest_prep_restaurants = average_prep_time.head(10)['restaurant_name']

# Get the cuisine type for these restaurants from the cleaned dataframe
longest_prep_cuisine = df_cleaned[df_cleaned['restaurant_name'].isin(top_longest_prep_restaurants)]['cuisine_type'].value_counts()
st.dataframe(longest_prep_cuisine)

average_prep_time = df.groupby(
    ['restaurant_name', 'cuisine_type']
)['food_preparation_time'].mean().reset_index()

average_prep_time['food_preparation_time'] = average_prep_time[
    'food_preparation_time'
].round(2)

average_prep_time = average_prep_time.sort_values(
    'food_preparation_time',
    ascending=False
)

average_prep_time['food_preparation_time'].nunique()

"""Observations

*  Food usually takes about 20 minutes to prepare.
*   The longest preparation time is 35 minutes.
*   The restaurants with the longest preparation time are Cipriani Le Specialita, Klong, Sushi, Choshi, Taro Sushi, and Kambi Ramen House.
*   Items from Japanese and Italian restaurants seem to take longer to prepare.

# Overall Observations for Question 6:

* The order ID's are evenly distributed with no outliers.
* The average cost of order is $16.50.
* The variables show that some categories are considerably more common than others, indicating that customer orders are not evenly distributed across all categories.
* The order cost and delivery time distributions show noticeable variation, meaning customers experience different order prices and delivery durations.
* This data provides critical overview and information of customer ordering patterns and FoodHub's operational characteristics, particularly in terms of cuisine preferences, spending, preparation time, and delivery time.

### **Question 7**: Which are the top 5 restaurants in terms of the number of orders received? [1 mark]
"""

df['restaurant_name'].value_counts()[:5]

plt.figure(figsize=(10, 6))
sns.barplot(x=df['restaurant_name'].value_counts()[:5].values, y=df['restaurant_name'].value_counts()[:5].index, palette='viridis')
plt.title('Top 5 Restaurants by Number of Orders')
plt.xlabel('Number of Orders')
plt.ylabel('Restaurant Name')
plt.tight_layout()
plt.show()

"""#### Observations:
* The chart shows that the top restaurants have more than 50 orders.
*   Shake Shack has the most orders with 219 orders.

* The top 5 restaurants are Shake Shack, The Meatball Shop, Blue Ribbon Sushi, Blue Ribbon Fried Chicken, and Parm.

* Shake shack is the most popular restaurant, therefore, it could be beneficial for FoodHub to partner with them for promotions.

### **Question 8**: Which is the most popular cuisine on weekends? [1 mark]
"""
weekend_orders = df[df['day_of_the_week'] == 'Weekend']

print(f"Count of orders on the weekend: {len(weekend_orders)}")

df.head()

popular_cuisine_weekend = weekend_orders['cuisine_type'].value_counts()
st.dataframe(popular_cuisine_weekend)

popular_cuisine = weekend_orders['cuisine_type'].value_counts()

popular_cuisine

df.groupby(['day_of_the_week'])['cuisine_type'].value_counts()

"""#### Observations:

*   American food is the most popular cuisine type on the weekends.

* American food is the most popular cuisine type during the week as well.

* Japanese food is the second most popular cuisine on weekends.

* There were 415 orders of American food on the weekend out of the 1351 total orders.

* Most popular cuisine type doesn't change between weekdays and weekends.

* American cuisine received 80 more orders than Japanese cuisine, This shows a noticeable preference for American food on weekends.

### **Question 9**: What percentage of the orders cost more than 20 dollars? [2 marks]
"""

orders_over_20 = (df['cost_of_the_order'] > 20).sum()
orders_20_or_less = (df['cost_of_the_order'] <= 20).sum()

labels = ['Orders > $20', 'Orders <= $20']
sizes = [orders_over_20, orders_20_or_less]
colors = ['#ff9999','#66b3ff']
explode = (0.1, 0)  # explode 1st slice

plt.figure(figsize=(8, 8))
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%',
        shadow=True, startangle=90)
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.title('Percentage of Orders by Cost Category')
plt.show()

plt.figure(figsize=(8, 6))
sns.barplot(x=labels, y=[s / sum(sizes) * 100 for s in sizes], palette=colors, hue=labels, legend=False)
plt.title('Percentage of Orders by Cost Category')
plt.xlabel('Cost Category')
plt.ylabel('Percentage of Orders (%)')
plt.ylim(0, 100) # Ensure y-axis goes from 0 to 100
plt.show()

orders_over_20 = (df['cost_of_the_order'] > 20).sum()
total_orders = df['cost_of_the_order'].count()
percentage_over_20 = (orders_over_20 / total_orders) * 100

print("Orders over $20:", orders_over_20)
print("Total orders:", total_orders)
print(f"Percentage over $20: {percentage_over_20:.2f}%")

"""#### Observations:


*   Nearly 30% of orders cost more than $20.

*   555 out of 1898 orders cost more than $20.

* The majority of orders cost $20 or less which means that prices are fairly reasonable.

### **Question 10**: What is the mean order delivery time? [1 mark]
"""

mean_delivery_time = df['delivery_time'].mean()

print(f"Mean delivery time: {mean_delivery_time:.2f} minutes")

plt.figure(figsize=(10, 6))
sns.histplot(df['delivery_time'], bins=15, kde=True)
plt.title('Distribution of Delivery Time')
plt.xlabel('Delivery Time (minutes)')
plt.ylabel('Frequency')
plt.show()

longest_delivery_time = df['delivery_time'].max()

print(f"Longest delivery time: {longest_delivery_time} minutes")

shortest_delivery_time = df['delivery_time'].min()

print(f"Shortest delivery time: {shortest_delivery_time} minutes")

"""#### Observations:
*   The mean delivery time is 24.16 minutes.
* The longest delivery time shown is 33 minutes.
* THe shortest delivery time is 15 minutes.
* The average delivery time is closer to the shortest so that means that most orders are delivered in a reasonable amount of time.

### **Question 11:** The company has decided to give 20% discount vouchers to the top 5 most frequent customers. Find the IDs of these customers and the number of orders they placed. [1 mark]
"""

top_5_customers = df['customer_id'].value_counts().head(5)
print("Top 5 most frequent customers:\n", top_5_customers)

top_5_customers = df['customer_id'].value_counts().head(5)
plt.figure(figsize=(10, 6))
sns.barplot(x=top_5_customers.values, y=top_5_customers.index.astype(str), palette='viridis', hue=top_5_customers.index.astype(str), legend=False)
plt.title('Top 5 Most Frequent Customers by Number of Orders')
plt.xlabel('Number of Orders')
plt.ylabel('Customer ID')
plt.tight_layout()
plt.show()

"""#### Observations:

* The customer with the most orders has the customer ID 52832. They have ordered 13 times.
* There is a clear difference between the most frequent customer and the other customers. The top customer places 3 more orders than the second-highest customer.

### Multivariate Analysis

### **Question 12**: Perform a multivariate analysis to explore relationships between the important variables in the dataset. (It is a good idea to explore relations between numerical variables as well as relations between numerical and categorical variables) [10 marks]

### Relationship between Cost of the Order and Delivery Time by Day of the Week
"""

df.head()

"""# Observations

* There does not appear to be a strong relationship between order cost and delivery time. Higher-priced orders do not consistently take longer to deliver.
* Day of the week appears to have a more obvious effect on delivery time than order cost.

### Correlation between Cost of Order and Delivery Time by Day of the Week
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Separate data for weekdays and weekends
weekday_df = df[df['day_of_the_week'] == 'Weekday']
weekend_df = df[df['day_of_the_week'] == 'Weekend']

# Calculate correlation matrices
corr_weekday = weekday_df[['cost_of_the_order', 'delivery_time']].corr()
corr_weekend = weekend_df[['cost_of_the_order', 'delivery_time']].corr()

plt.figure(figsize=(14, 6))

# Heatmap for Weekday
plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
sns.heatmap(corr_weekday, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix (Weekday)')

# Heatmap for Weekend
plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
sns.heatmap(corr_weekend, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix (Weekend)')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

for day in df['day_of_the_week'].unique():
    data = df[df['day_of_the_week'] == day]

    plt.scatter(data['cost_of_the_order'], data['delivery_time'], label=day)

plt.xlabel('Cost of the Order ($)')
plt.ylabel('Delivery Time (minutes)')
plt.title('Cost of Order vs Delivery Time by Day of the Week')
plt.legend()
plt.show()

"""Observations:

*  There is a significant difference between the costs and delivery times between the weekends and weekdays.

*  There is a strong correlation between delivery times and cost of order.

### Relationship between Food Preparation Time and Delivery Time
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the correlation matrix for food_preparation_time and delivery_time
correlation_matrix = df[['food_preparation_time', 'delivery_time']].corr()

plt.figure(figsize=(6, 5))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation between Food Preparation Time and Delivery Time')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='food_preparation_time', y='delivery_time', alpha=0.7)
plt.title('Food Preparation Time vs. Delivery Time')
plt.xlabel('Food Preparation Time (minutes)')
plt.ylabel('Delivery Time (minutes)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

correlation_value = correlation_matrix.loc['food_preparation_time', 'delivery_time']
print(f"Correlation coefficient between food preparation time and delivery time: {correlation_value:.3f}")

"""#### Observations:
*   There isn't a direct correlation between food preparation time and delivery time.

* There is no predictable change in delivery time.

* Correlation coefficient is approximately 0.011 which means there is a weak relationship.

### Relationship between Rating and Delivery/Preparation Times
"""

df.groupby(['rating'])['total_time'].mean()

rated_df = df[df['rating'] != 'Not given'].copy()
rated_df['rating'] = pd.to_numeric(rated_df['rating'])

plt.figure(figsize=(10, 6))
sns.scatterplot(data=rated_df, x='rating', y='total_time', alpha=0.7)
plt.title('Rating vs. Total Time')
plt.xlabel('Rating')
plt.ylabel('Total Time (minutes)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

rated_df = df[df['rating'] != 'Not given']
rated_df['rating'] = pd.to_numeric(rated_df['rating'])

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
sns.boxplot(data=rated_df, x='rating', y='delivery_time', palette='viridis')
plt.title('Delivery Time by Customer Rating')
plt.xlabel('Rating')
plt.ylabel('Delivery Time (minutes)')

plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
sns.boxplot(data=rated_df, x='rating', y='food_preparation_time', palette='plasma')
plt.title('Food Preparation Time by Customer Rating')
plt.xlabel('Rating')
plt.ylabel('Food Preparation Time (minutes)')

plt.tight_layout()
plt.show()

correlation_matrix_rating_delivery = rated_df[['rating', 'delivery_time']].corr()

plt.figure(figsize=(6, 5))
sns.heatmap(correlation_matrix_rating_delivery, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation between Customer Rating and Delivery Time')
plt.show()

"""#### Observations:
*  There is not a significant relationship between customer rating and delivery time.
* The distributions have a lot of overlap in delivery time distributions across rating categories.

### **Question 13:** The company wants to provide a promotional offer in the advertisement of the restaurants. The condition to get the offer is that the restaurants must have a rating count of more than 50 and the average rating should be greater than 4. Find the restaurants fulfilling the criteria to get the promotional offer. [3 marks]
"""

rated_restaurants = df[df['rating'] != 'Not given'].copy()
rated_restaurants['rating'] = pd.to_numeric(rated_restaurants['rating'])

restaurant_ratings = rated_restaurants.groupby('restaurant_name')['rating'].agg(
    rating_count='count',
    average_rating='mean'
).reset_index()

promotional_restaurants = restaurant_ratings[
    (restaurant_ratings['rating_count'] > 50) &
    (restaurant_ratings['average_rating'] > 4)
].copy()

promotional_restaurants['average_rating'] = promotional_restaurants['average_rating'].round(2)

promotional_restaurants

rated_restaurants = df[df['rating'] != 'Not given'].copy()
rated_restaurants['rating'] = pd.to_numeric(rated_restaurants['rating'])

restaurant_ratings = rated_restaurants.groupby('restaurant_name')['rating'].agg(
    rating_count='count',
    average_rating='mean'
).reset_index()

promotional_restaurants = restaurant_ratings[
    (restaurant_ratings['rating_count'] > 50) &
    (restaurant_ratings['average_rating'] > 4)
].copy()

promotional_restaurants['average_rating'] = promotional_restaurants['average_rating'].round(2)

promotional_restaurant_names = promotional_restaurants['restaurant_name'].tolist()

# Get the cuisine types for these promotional restaurants from the original DataFrame
promotional_cuisine_types = df[df['restaurant_name'].isin(promotional_restaurant_names)][['restaurant_name', 'cuisine_type']].drop_duplicates()

print("Cuisine types for promotional restaurants:")
st.dataframe(promotional_cuisine_types)

cuisine_counts = promotional_cuisine_types['cuisine_type'].value_counts().reset_index()
cuisine_counts.columns = ['cuisine_type', 'num_restaurants']

plt.figure(figsize=(10, 6))
sns.barplot(x='cuisine_type', y='num_restaurants', data=cuisine_counts, palette='viridis', hue='cuisine_type', legend=False)
plt.title('Number of Promotional Restaurants by Cuisine Type')
plt.xlabel('Cuisine Type')
plt.ylabel('Number of Promotional Restaurants')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""#### Observations:
*   The restaurants with a rating over 4 with a rating count over 50 are Blue Ribbon Fried Chicken, Blue Ribbon Sushi, Shake Shack, and The Meatball Shop. These restaurants should get the promotional offer.

* A commonality among these top-performing restaurants is that three out of five of the restaurants serve American cuisine, and the other serves Japanese cuisine, both of which are among the most popular cuisine types overall in the dataset. The last one serves italian food which is in the top 3 most popular cuisine type.

### **Question 14:** The company charges the restaurant 25% on the orders having cost greater than 20 dollars and 15% on the orders having cost greater than 5 dollars. Find the net revenue generated by the company across all orders. [3 marks]
"""

def calculate_revenue(cost):
    if cost > 20:
        return cost * 0.25
    elif cost > 5:
        return cost * 0.15
    else:
        return 0
df['revenue'] = df['cost_of_the_order'].apply(calculate_revenue)

net_revenue = df['revenue'].sum()

print(f"Net revenue generated: ${net_revenue:.2f}")

df[['cost_of_the_order', 'revenue']]

def calculate_revenue(cost):
    if cost > 20:
        return cost * 0.25
    elif cost > 5:
        return cost * 0.15
    else:
        return 0

df['revenue'] = df['cost_of_the_order'].apply(calculate_revenue)

plt.figure(figsize=(12, 7))
sns.scatterplot(data=df, x='cost_of_the_order', y='revenue', alpha=0.7)
plt.title('Revenue Generated vs. Cost of the Order')
plt.xlabel('Cost of the Order ($)')
plt.ylabel('Revenue Generated ($)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.axvline(x=5, color='r', linestyle='--', label='Commission Threshold ($5)')
plt.axvline(x=20, color='g', linestyle='--', label='Commission Threshold ($20)')
plt.legend()
plt.show()

"""Observation:

* The orders that generate the highest revenue are ones that cost more than $20.

* Orders costing $5 or less do not generate revenue for the company.

* The net revenue is $6,166.30

* The revenue generated from each order increases as the cost of the order increases, especially for orders above $20.

* The dataset contains 1,898 orders, so the $6,166.30 represents the combined commission earned across the entire dataset.

### **Question 15:** The company wants to analyze the total time required to deliver the food. What percentage of orders take more than 60 minutes to get delivered from the time the order is placed? (The food has to be prepared and then delivered.) [2 marks]
"""

percentage_over_60 = (df['total_time'] > 60).mean() * 100

print(f"Percentage of orders taking more than 60 minutes: {percentage_over_60:.2f}%")

"""Observations:

* 10.54% of orders take longer than 60 minutes to fulfill from the time it is ordered to the time it is delivered.

* A majority of orders take less than 60 minutes to fulfill.

* Although most orders are completed within an hour, a noticeable amountof orders take longer than 60 minutes.

* Longer wait times could impact customer satisfaction.

### **Question 16:**
The company wants to analyze the delivery time of the orders on weekdays and weekends. How does the mean delivery time vary during weekdays and weekends? [2 marks]
"""

df['day_type'] = df['day_of_the_week'].apply(
    lambda x: 'Weekend' if x == 'Weekend' else 'Weekday'
)

df.groupby('day_type')['delivery_time'].agg(
    ['mean', 'median', 'min', 'max']
)

import matplotlib.pyplot as plt

df.boxplot(column='delivery_time', by='day_type')

plt.xlabel('Day Type')
plt.ylabel('Delivery Time (minutes)')
plt.title('Delivery Time: Weekdays vs Weekends')
plt.suptitle('')
plt.show()

from scipy.stats import ttest_ind

weekday = df[df['day_of_the_week'] == 'Weekday']['delivery_time']
weekend = df[df['day_of_the_week'] == 'Weekend']['delivery_time']

t_stat, p_value = ttest_ind(weekday, weekend, equal_var=False)

print("T-statistic:", t_stat)
print("P-value:", p_value)

"""#### Observations:



*   During the weekday, it typically takes longer for delivery.
*   There is a bigger difference between the wait times for delivery on the weekends.
* Orders take almost 6 minutes longer to deliver on weekdays than on weekends.
* Overall, delivery times are faster on weekends than on weekdays.
* Mean delivery time on weekdays is 28 minutes and on weekends it is 22 minutes.
* The minimum and maximum time for delivery is more consistent than the minimum and maximum time for delivery on the weekends.
* The fastest delivery occurs on weekends (15 minutes), which is 9 minutes faster than the fastest weekday delivery.

### Conclusion and Recommendations for question 16



*   Investigate why weekday deliveries take longer than weekend deliveries.
*   FoodHub might want to increase the number of delivery drivers on weekdays.
* FoodHub could focus on improving restaurant preparation and delivery coordination during weekdays.
* FoodHub should monitor weekday and weekend delivery times to determine whether operational changes that are made are improving performance.

### **Question 17:** What are your conclusions from the analysis? What recommendations would you like to share to help improve the business? (You can use cuisine type and feedback ratings to drive your business recommendations.) [6 marks]

### Conclusions:

*  A lot of customers do not provide ratings.
*  Delivery times varied greatly on the weekends.
*  The cuisine types that are most popular are American, Japanese, and Italian.
* There is a large cost difference between cuisines.
* Food delivery and preparation times do not impact customer rating much.
* There is a statistically significant difference in delivery times between weekdays and weekends. The t-test produced a t-statistic of 33.262190207973624 and a p-value of 2.5737146093950945e-184. This is way below the 5% significance level.
* Most of the orders are reasonably priced.
* FoodHub has a large customer base, with 1,898 orders from 1,200 unique customers and 178 restaurants across 14 different cuisine types.
* Customers have a wide variety of cuisine types to choose from.
* Delivery time is the area that FoodHub should work the hardest to improve.

### Recommendations:

* FoodHub could offer customers loyalty points or a small discount on their next order in exchange for rating their orders a certain number of times. This would encourage more customers to provide feedback, help gather information to enhance satisfaction, while also encouraging repeat purchases.

* FoodHub should use demand forecasting to determine times where delivery will be most popular and provide more delivery personnel during that time and provide incentives for delivery personnel to work during those times.

* FoodHub should use the popular cuisine (American food, Japanese Food, Italian Food), customer rating, and delivery performance to attract customers and feature these types of cuisines. Offer targeted promotions where discounts or deals are given from these restauarants. Along with the discounts from the restaurants, FoodHub should also provide discounts or deals by FoodHub on delivery of these types of cuisines.

*  FoodHub should try to reduce the delivery times on the weekdays. This will provide a more consistent and reliable experience and therefore bring more repeat customers.  In general, improving the delivery time should be a point of emphasis.

* FoodHub should monitor the restaurants with longer preparation times and help these restaurants identify ways to improve their preparation time.

---
"""
